images_dir: data/few_data/train
masks_dir: data/few_data/train_masks
image_size: [256, 256]
val_split: 0.1
batch_size: 8
learning_rate: 0.0001
epochs: 2
model_save_path: models/unet_carvana.pth
in_channels: 3
out_channels: 1